/** Shared UI labels — Title Case for controls/headers, sentence case for body copy. */

import { LEARNING_PARTNER } from '../constants/branding'

export const UI = {
  saveAttendance: 'Save Attendance',
  saveDailyAttendance: 'Save Daily Attendance',
  overwriteAttendance: 'Overwrite Attendance',
  keepEditing: 'Keep Editing',
  importAnotherNow: 'Import Another Now',
  viewDashboard: 'View Dashboard',
  confirmSaveAttendance: 'Confirm Save Attendance',
  confirmOverwriteAttendance: 'Confirm Overwrite Attendance',
  confirmSaveNewClass: 'Confirm Save — New Class',
  afterSave: 'After Save',
  noSessionRecord: 'No Session Record',
  notInRoster: 'Not in Roster',
  presentStreakReset: 'Present · Streak Reset',
  absentStreakUp: 'Absent · Streak Up',
  reportRequired: 'Report Required',
  officialReporting: 'Official Reporting',
  officialReportingRequired: 'Official Reporting Required',
  markAsReported: 'Mark as Reported',
  reportingThresholds: 'Reporting Thresholds',
  attendanceSaved: 'Attendance Saved',
  session: 'Session',
  summary: 'Summary',
  student: LEARNING_PARTNER.singularTitle,
  learningPartner: LEARNING_PARTNER.singularTitle,
  learningPartners: LEARNING_PARTNER.pluralTitle,
  current: 'Current',
  change: 'Change',
  streak: 'Streak',
  total: 'Total',
}
