/** Shared UI labels — Title Case for controls/headers, sentence case for body copy. */

import { LEARNING_PARTNER } from '../constants/branding'

export const UI = {
  saveAttendance: 'Save Attendance',
  saveDailyAttendance: 'Save Daily Attendance',
  overwriteAttendance: 'Overwrite Attendance',
  keepEditing: 'Keep Editing',
  importAnotherNow: 'Import Another Now',
  viewDashboard: 'View Dashboard',
  confirmSaveAttendance: 'Confirm Save Attendance',
  confirmOverwriteAttendance: 'Confirm Overwrite Attendance',
  confirmSaveNewClass: 'Confirm Save — New Class',
  afterSave: 'After Save',
  noSessionRecord: 'No Session Record',
  notInRoster: 'Not in Roster',
  presentStreakReset: 'Present · Streak Reset',
  absentStreakUp: 'Absent · Streak Up',
  absentRosterUnchanged: 'Absent · Roster Unchanged',
  absentFirstSession: 'Absent · First mark (this session)',
  presentFirstSession: 'Present · First mark (this session)',
  reportRequired: 'Report Required',
  officialReporting: 'Official Reporting',
  officialReportingRequired: 'Official Reporting Required',
  markAsReported: 'Mark as Reported',
  reportingThresholds: 'Reporting Thresholds',
  attendanceSaved: 'Attendance Saved',
  session: 'Session',
  summary: 'Summary',
  student: LEARNING_PARTNER.singularTitle,
  learningPartner: LEARNING_PARTNER.singularTitle,
  learningPartners: LEARNING_PARTNER.pluralTitle,
  current: 'Current',
  change: 'Change',
  streak: 'Streak',
  total: 'Total',
  classesAndRosters: 'Classes & Rosters',
  priorNotice: 'Prior Notice',
  bulkEditAbsenceCounts: 'Bulk Edit Absence Counts',
  clearAllOverrides: 'Clear All Overrides',
  history: 'History',
  clearHistory: 'Clear History',
  status: 'Status',
  actions: 'Actions',
  learningPartnerName: 'Learning Partner Name',
  signIn: 'Sign In',
  signOut: 'Sign Out',
  createAccount: 'Create Account',
  generateFeedback: 'Generate Feedback',
  generateFeedbackAndRefine: 'Generate Feedback & Refine',
  traitsAndNotes: 'Traits & Notes',
  generatedFeedback: 'Generated Feedback',
  saveFeedback: 'Save Feedback',
  feedbackSaved: 'Saved Feedback',
  feedbackExtraNotes: 'Extra Notes',
  feedbackSearchPlaceholder: 'Search Learning Partner…',
  feedbackComposeNotes: 'Compose Notes (Optional)',
  parseJson: 'Parse JSON',
  scanScreenshot: 'Scan Screenshot',
  pasteScreenshot: 'Paste Screenshot',
  chooseImage: 'Choose Image',
  continueReview: 'Continue Review',
  discardChanges: 'Discard Changes',
  markAllAbsent: 'Mark All Absent',
  markAllPresent: 'Mark All Present',
  openReporting: 'Open Reporting',
  scanEngineLabel: 'Vision Engine',
  scanEngineLocal: 'Local',
  scanEngineCloud: 'Cloud',
  clearQueue: 'Clear Queue',
  scanningQueue: 'Scanning Queue…',
  saveAgain: 'Save Again',
  stayOnThisItem: 'Stay on This Item',
  goToNextNow: 'Go to Next',
  refineWithAi: 'Refine with AI',
  done: 'Done',
  deleteSession: 'Delete Session',
  removeFromModule: 'Remove from This Module',
  confirmRemoveFromModule: 'Remove from This Module?',
  confirmDeleteSession: 'Delete Session?',
  tableNameSearchPlaceholder: 'Filter names…',
  tableNameSearchFuzzyHint: 'Includes close name matches (90%+ similarity)',
  dashboardSearchPlaceholder: 'Name, class, or module…',
  bulkScreenshotsBeta: 'Bulk Screenshots (beta)',
  syncPortalClasses: 'Sync from College Portal',
  portalMonitoringTitle: 'Sync from College Portal',
  portalMonitoringPull: 'Pull from portal',
  portalMonitoringRefresh: 'Refresh from portal',
  portalMonitoringCacheHint: 'Showing cached portal data',
  portalMonitoringPulled: 'Portal data pulled',
  portalMonitoringSaved: 'Hub updated from portal',
  portalMonitoringDescription:
    'Pull uses your .env portal login. Pick a class (programme shown once per class) — the Learning Partner list is shared across all modules — then switch subjects to review P/A and session imports.',
  portalClassSyncTitle: 'Link College Portal Classes',
  portalClassSyncPull: 'Pull Class List',
  portalClassSyncSave: 'Review sync',
  portalClassSyncConfirm: 'Confirm sync',
  portalClassSyncConfirmTitle: 'Confirm college portal sync',
  portalClassSyncSaved: 'Portal sync saved',
  portalClassSyncPulled: 'Class list pulled successfully',
  portalClassSyncDescription:
    'Pull classes from the college portal, link each row to a hub class (or create a new one), then expand a class to choose modules. Matched modules are checked by default. Review sync loads portal rosters and attendance, then opens a student-by-student preview per selected module before anything is saved.',
  pullPortalRoster: 'Pull Portal Roster',
  portalRosterPulled: 'Portal roster pulled successfully',
  portalRosterNotLinked: 'Link this class to the college portal before pulling its roster.',
  pullPortalAttendance: 'Pull Portal Attendance',
  portalAttendancePulled: 'Portal attendance applied',
  portalAttendanceNotLinked:
    'Link this class to the college portal before pulling attendance.',
}

/** e.g. "3 Learning Partners" */
export function formatLpCount(count) {
  return `${count} ${count === 1 ? UI.learningPartner : UI.learningPartners}`
}
